### ISSUE TITLE
Menu dialog, 'open with'

### ISSUE THREAD

**Issue by ghost** [Havoc-OS/android_frameworks_base#117]
How do you fix this problem? I just changed the framework, then there was an error in the "open with" menu.
The problem occurs only in SELinux Enforcing, for SELinux Permissive there are no errors.

Log error below:

log 1:

FATAL EXCEPTION: main
PID: 14990
java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.attachApplication(android.app.IApplicationThread, long)' on a null object reference
	at android.app.ActivityThread.attach(ActivityThread.java:6560)
	at android.app.ActivityThread.main(ActivityThread.java:6685)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
	
	log 2:
	
Error reporting crash
java.lang.NullPointerException: Attempt to invoke interface method 'void android.app.IActivityManager.handleApplicationCrash(android.os.IBinder, android.app.ApplicationErrorReport$ParcelableCrashInfo)' on a null object reference
	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:143)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
	at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)

**Comment by ghost** [comment]
I hope someone helps me :(
