### ISSUE TITLE
null animation checks?

### ISSUE THREAD

**Issue by alex9yust** [Havoc-OS/android_frameworks_base#119]
https://github.com/Havoc-OS/android_frameworks_base/blob/8603fc1e2501ab59f480700bfbe5caad75510fa3/packages/SystemUI/src/com/android/systemui/statusbar/phone/CollapsedStatusBarFragment.java#L439
 
--------- beginning of crash
06-07 19:03:44.375  2333  2333 E AndroidRuntime: FATAL EXCEPTION: main
06-07 19:03:44.375  2333  2333 E AndroidRuntime: Process: com.android.systemui, PID: 2333
06-07 19:03:44.375  2333  2333 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewPropertyAnimator a
ndroid.view.View.animate()' on a null object reference
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at com.android.systemui.statusbar.phone.CollapsedStatusBarFragment.animateShow(CollapsedStatusBarF
ragment.java:439)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at com.android.systemui.statusbar.phone.CollapsedStatusBarFragment.showSystemIconArea(CollapsedSta
tusBarFragment.java:352)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at com.android.systemui.statusbar.phone.CollapsedStatusBarFragment.onViewCreated(CollapsedStatusBa
rFragment.java:190)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1313)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:883)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:100)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:214)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:7356)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
06-07 19:03:44.375  2333  2333 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
06-07 19:03:44.375  2753  2753 I CallNotifier: onCallForwardingIndicatorChanged(): subId=2, visible=N

**Comment by alex9yust** [comment]
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: com.android.systemui, PID: 2339
AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setAlpha(float)' on a null object reference
AndroidRuntime: <->at com.android.systemui.statusbar.phone.PhoneStatusBarTransitions.applyMode(PhoneStatusBarTransitions.java:113)
AndroidRuntime: <->at com.android.systemui.statusbar.phone.PhoneStatusBarTransitions.<init>(PhoneStatusBarTransitions.java:56)
AndroidRuntime: <->at com.android.systemui.statusbar.phone.StatusBarWindowView.setStatusBarView(StatusBarWindowView.java:306)
AndroidRuntime: <->at com.android.systemui.statusbar.phone.StatusBar.lambda$makeStatusBarView$4$StatusBar(StatusBar.java:1026)
AndroidRuntime: <->at com.android.systemui.statusbar.phone.-$$Lambda$StatusBar$dy7qc-M4vmC01_Sduz1UMseDUmo.onFragmentViewCreated(Unknown Source:2)
AndroidRuntime: <->at com.android.systemui.fragments.FragmentHostManager.lambda$onFragmentViewCreated$0(FragmentHostManager.java:140)
AndroidRuntime: <->at com.android.systemui.fragments.-$$Lambda$FragmentHostManager$OsWXqtcfRJZBAvEEeN8CG6EN5T4.accept(Unknown Source:6)
AndroidRuntime: <->at java.util.ArrayList.forEach(ArrayList.java:1262)
AndroidRuntime: <->at com.android.systemui.fragments.FragmentHostManager.onFragmentViewCreated(FragmentHostManager.java:140)
AndroidRuntime: <->at com.android.systemui.fragments.FragmentHostManager.access$000(FragmentHostManager.java:49)
AndroidRuntime: <->at com.android.systemui.fragments.FragmentHostManager$1.onFragmentViewCreated(FragmentHostManager.java:80)
AndroidRuntime: <->at android.app.FragmentManagerImpl.dispatchOnFragmentViewCreated(FragmentManager.java:3342)
AndroidRuntime: <->at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
AndroidRuntime: <->at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
AndroidRuntime: <->at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
AndroidRuntime: <->at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
AndroidRuntime: <->at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
AndroidRuntime: <->at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
AndroidRuntime: <->at android.os.Handler.handleCallback(Handler.java:883)
AndroidRuntime: <->at android.os.Handler.dispatchMessage(Handler.java:100)
AndroidRuntime: <->at android.os.Looper.loop(Looper.java:214)
AndroidRuntime: <->at android.app.ActivityThread.main(ActivityThread.java:7356)
AndroidRuntime: <->at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: <->at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
AndroidRuntime: <->at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:915)
